package:
  name: giropops
  version: 0.1.0
  description: friendly little webserver
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - gcc
      - musl-dev
      - python3
      - python3-dev
      - py3-pip
      - py3-virtualenv

  accounts:
    groups:
      - groupname: nonroot
        gid: 65532
    users:
      - username: nonroot
        uid: 65532
    run-as: 65532

pipeline:
  - name: Build Python application
    runs: |
      WEBAPPDIR="${{targets.destdir}}/usr/share/webapps/giropops"
      mkdir -p "${WEBAPPDIR}"
      echo "#!/usr/share/webapps/giropops/venv/bin/python3" > "${WEBAPPDIR}/giropops"
      cat app.py >> "${WEBAPPDIR}/giropops"
      chmod +x "${WEBAPPDIR}/giropops"
      mkdir "${WEBAPPDIR}/logs"
      cp -r static "${WEBAPPDIR}"
      cp -r templates "${WEBAPPDIR}"
      ls -la "${WEBAPPDIR}"
      virtualenv "${WEBAPPDIR}/venv"
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install -r requirements.txt"